server:
  port: 8082

db:
  h2:
    url: h2url
    username: namory
    password: nam_pass
  mysql:
    url: mysqlurl
    username: bakary
    password: bak_pass


management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - refresh
          - health